name: Shankar G Raman
favicon: null
layout_spectrum: 0.00482
typography_spectrum: 0.42871
title: Immortalise your expressions and emotions!
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151515'
    - '#678db2'
    - '#393939'
    - '#ad906e'
    - '#fffff7'
  brandStrength: 0.1875
  lightness: 0.9169792023021728
  saturation: 0.25306608784012496
  rhythmicContrast: 0.75
purpose: []
