name: Shankar G Raman
favicon: null
layout_spectrum: 0
typography_spectrum: 0.50193
title: Immortalise your expressions and emotions!
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bc97a9'
    - '#3c38ff'
    - '#0e0f23'
    - '#a31f2c'
  brandStrength: 0
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 0
purpose: []
